models.py
import datetime
from flask import url_for
from app import db

class PlaceForRent(db.Document):
    created_at = db.DateTimeField(default=datetime.datetime.now, required=True)
    address=db.ReferenceField('Address')
    price=db.IntField()
    num_rooms=db.IntField()
    num_bathrooms=db.IntField()
    sqft=db.DecimalField(precision=1)
    unit_number=db.StringField(max_length=255, default="")

    def get_absolute_url(self):
        return url_for('place', kwargs={"id": self.id})

    def __unicode__(self):
        if(self.address):
            return self.address.block_number+" "+self.address.street_name
        else:
            return self.unit_number

    meta = {
            'allow_inheritance': True,
            }

# Reuse the address for similar blocks, using postal code as the primary key
class Address(db.Document):
    block_number=db.StringField(max_length=255)
    street_name=db.StringField(max_length=255, required=True)
    postal_code=db.StringField(primary_key=True, max_length=255, required=True)
    city=db.StringField(max_length=255)
    country=db.StringField(max_length=255)
    coordinates=db.StringField(max_length=255)

    def __unicode__(self):
        return self.block_number+" "+self.street_name+" "+self.postal_code


#address=Address(block_number="546",street_name="Woodlands Drive 16",postal_code="730546",city="Singapore",country="Singapore")
#place=PlaceForRent(price=2000,num_rooms=3,num_bathrooms=2,sqft=108.5,unit_number="#10-31")

__init__.py
from flask import Flask
from flask import make_response, jsonify
from flask.ext import restful
from flask.ext.mongoengine import MongoEngine
from mongoengine import connect
app = Flask(__name__)
api = restful.Api(app)

DB_NAME = 'sampledb'
DB_USERNAME = 'taimin'
DB_PASSWORD = 'password'
DB_HOST_ADDRESS = 'ds035270.mongolab.com:35270/sampledb'

app.config["MONGODB_DB"] = DB_NAME
#app.config['MONGODB_SETTINGS'] = {'db':"testdb"}
app.config["SECRET_KEY"] = "KeepThisS3cr3t"
connect(DB_NAME, host='mongodb://' + DB_USERNAME + ':' + DB_PASSWORD + '@' + DB_HOST_ADDRESS)
db = MongoEngine(app)

@app.errorhandler(404)
def not_found(error):
    return make_response(jsonify( { 'error': 'Unable to process request' } ), 404)

def register_blueprints(app):
    # Prevents circular imports
    from app.views import places
    from app.api import place_api
    app.register_blueprint(places)
    app.register_blueprint(place_api)

register_blueprints(app)

if __name__ == '__main__':
    import os
    port = int(os.environ.get('PORT', 5000))
    app.run(debug=True, port=port)

views.py
#from app import app
from flask import Blueprint, request, redirect, render_template, url_for
from flask.ext.mongoengine.wtf import model_form
from flask.views import MethodView
from app.models import PlaceForRent, Address


places = Blueprint('places', __name__, template_folder='templates')


class ListView(MethodView):

    def get(self):
        places = PlaceForRent.objects.all()
        return render_template('places/list.html', places=places)


class DetailView(MethodView):

    #form = model_form(PlaceForRent, exclude=['created_at'])

    def get_context(self, place_id=None):
        #place = PlaceForRent.objects.get_or_404(id=place_id)
        #form = self.form(request.form)

        #context = {
        #    "place": place,
        #    "form": form
        #}
        #return context

        form_cls = model_form(PlaceForRent, exclude=['created_at'])
        form_cls.address.label_attr='descrizione'

        if place_id:
            place = PlaceForRent.objects.get_or_404(id=place_id)
            if request.method == 'POST':
                form = form_cls(request.form, inital=place._data)
            else:
                form = form_cls(obj=place)
        else:
            place = PlaceForRent()
            form = form_cls(request.form)

        context = {
            "place": place,
            "form": form,
            "create": place_id is None
        }
        return context

    def get(self, place_id):
        #place = PlaceForRent.objects.get_or_404(id=place_id)
        if('delete' in request.path):
            print "HIHI"
            return self.delete(place_id)
        else:
            context = self.get_context(place_id)
            #return render_template('places/details.html', place=place)
            return render_template('places/details.html', **context)

    def post(self, place_id):
        context = self.get_context(place_id)
        form = context.get('form')
        form.address.label_attr='descrizione'

        if form.validate():
            place = context.get('place')
            form.populate_obj(place)
            place.save()

            return redirect(url_for('places.list'))

        return render_template('places/list.html', **context)

    def delete(self, place_id):
        context = self.get_context(place_id)
        place = context.get('place')
        place.delete()
        return redirect(url_for('places.list'))

# Register the urls
places.add_url_rule('/', view_func=ListView.as_view('list'))
places.add_url_rule('/<place_id>/', view_func=DetailView.as_view('detail'))
#places.add_url_rule('/create/', defaults={'place_id': None}, view_func=DetailView.as_view('create'))
places.add_url_rule('/edit/<place_id>/', view_func=DetailView.as_view('edit'))
places.add_url_rule('/delete/<place_id>/', view_func=DetailView.as_view('delete'))

templates/_forms.html
{% macro render(form) -%}
<fieldset>
{% for field in form %}
{% if field.type in ['CSRFTokenField', 'HiddenField'] %}
  {{ field() }}
{% else %}
  <div class="clearfix {% if field.errors %}error{% endif %}">
    {{ field.label }}
    <div class="input">
      {% if field.name == "address" %}
        {{ field(rows=10, cols=40) }}
      {% else %}
        {{ field() }}
      {% endif %}
      {% if field.errors or field.help_text %}
        <span class="help-inline">
        {% if field.errors %}
          {{ field.errors|join(' ') }}
        {% else %}
          {{ field.help_text }}
        {% endif %}
        </span>
      {% endif %}
    </div>
  </div>
{% endif %}
{% endfor %}
</fieldset>
{% endmacro %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>My Test App</title>
    <link href="http://bootstrapdocs.com/v1.4.0/bootstrap.css" rel="stylesheet">
    <link rel="stylesheet" href="static/css/spinner.css">
    <style>.content {padding-top: 80px;}</style>
  </head>

  <body>

    {%- block topbar -%}
    <div class="topbar" data-dropdown="dropdown">
      <div class="fill">
        <div class="container">
          <h2>
               <a href="{{ url_for('places.list') }}" class="brand">My TestApp Admin</a>
          </h2>
          <ul class="nav secondary-nav">
            <li class="menu">
               <a href="/#/create" class="btn primary">Create new place</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
    {%- endblock -%}

    <div class="container">
      <div class="content">
        {% block page_header %}{% endblock %}
        {% block content %}{% endblock %}
      </div>
    </div>
    {% block js_footer %}{% endblock %}
  </body>
</html>

templates/places/details.html
{% extends "base.html" %}
{% import "_forms.html" as forms %}

{%- block topbar -%}
<div class="topbar" data-dropdown="dropdown">
  <div class="fill">
    <div class="container">
      <h2>
           <a href="{{ url_for('places.list') }}" class="brand">My TestApp Admin</a>
      </h2>
      <ul class="nav secondary-nav">
        <li class="menu">
           <a href="{{ url_for('places.create') }}" class="btn primary">Create new place</a>
        </li>
      </ul>
    </div>
  </div>
</div>
{%- endblock -%}

{% block content %}
  <h2>
    {% if create %}
      Add new Place
    {% else %}
      Edit Place
    {% endif %}
  </h2>
  <form action="." method="post">
    {{ forms.render(form) }}
    <div class="actions">
      <input type="submit" class="btn primary" value="Save">
    </div>
  </form>
{% endblock %}

templates/places/list.html
{% extends "base.html" %}

{% block content %}
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.2.15/angular.min.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.2.15/angular-route.js"></script>

<!--1.2.15-->
<!--Making Calls to Backend via API using AngularJS-->
<div ng-app="PlaceApp">
  <div ng-view></div>
</div>
<script src="/static/js/place.js"></script>
<!--
<h2>Direct Calls to Backend</h2>
  <table  class="condensed-table zebra-striped">
    <thead>
      <th>Location</th>
      <th>Created</th>
      <th>Price</th>
      <th>Actions</th>
    </thead>
    <tbody>
    {% for place in places %}
      <tr>
        <th><a href="{{ url_for('places.edit', place_id=place.id) }}">{{ place}}</a></th>
        <td>{{ place.created_at.strftime('%Y-%m-%d') }}</td>
        <td>{{place.price}}</td>
        <td><a href="{{ url_for('places.edit', place_id=place.id) }}" class="btn primary">Edit</a><a href="{{ url_for('places.delete', place_id=place.id) }}" class="btn primary">Delete</a></td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
-->
{% endblock %}

templates/places/temp_details.html
{% extends "base.html" %}
{% import "_forms.html" as forms %}

{%- block topbar -%}
<div class="topbar" data-dropdown="dropdown">
  <div class="fill">
    <div class="container">
      <h2>
           <a href="{{ url_for('places.list') }}" class="brand">My TestApp Admin</a>
      </h2>
      <ul class="nav secondary-nav">
        <li class="menu">
           <a href="{{ url_for('places.create') }}" class="btn primary">Create new place</a>
        </li>
      </ul>
    </div>
  </div>
</div>
{%- endblock -%}

{% block page_header %}
  <div class="page-header">
    <h1>{{ place }}</h1>
  </div>
{% endblock %}

{% block content %}
  <p>{{ place.unit_number }} {{place.address.block_number}} {{place.address.street_name}}<p>
  <p>Postal Code: {{place.address.postal_code}}<p>
  <p>Created at: {{ place.created_at.strftime('%H:%M %Y-%m-%d') }}</p>
  <hr>
  <h2>Info</h2>
       <p>Rental Price: <strong>${{ place.price }}</strong> <small>on {{ place.created_at.strftime('%H:%M %Y-%m-%d') }}</small></p>

  <hr>
  <h2>Edit details</h2>
  <form action="." method="post">
    {{ forms.render(form) }}
    <div class="actions">
      <input type="submit" class="btn primary" value="Edit">
    </div>
  </form>
{% endblock %}